### ISSUE TITLE
load weights

### ISSUE THREAD

**Issue by srinadhu** [zcrwind/PredNet_pytorch#1]
Hello, load_weights.py is throwing an error saying:
                KeyError: "Unable to open object (object 'model_weights' doesn't exist)"

can you please let me know @zcrwind  or upload the pytorch weights itself?

**Comment by Moniruzzaman1988** [comment]
Hi while running train.sh, data_utils.py throwing an error as bellow:  

File "/home/teleoperation/PredNet_pytorch/data_utils.py", line 139, in dataLoader
    image_dataset = SequenceGenerator(self.data_file, self.source_file, self.args.num_timeSteps, self.args.shuffle, None, self.output_mode, self.sequence_start_mode, self.N_seq, self.args.data_format)
  File "/home/teleoperation/PredNet_pytorch/data_utils.py", line 51, in __init__
    varName = resList[0]
IndexError: list index out of range
